### PR TITLE
Fixes #15 - use CASCADE for dropping views

### PR DESCRIPTION
**Pull request by anneFly**

### CODE REVIEW

**Comment by anneFly** [comment]
@syphar what do you think? I first wanna have an internal review before I push it upstream. Can you think of any edge cases maybe where this will be bad? Also, do you think the tests are understandable? Or should I add more comments?

**Comment by syphar** [comment]
@anneFly are we sure that all the child-views are recreated afterwards? Not sure about the resolving order here

**Comment by syphar** [comment]
- ah wait. I think this works. 
- tests look good and understandable to me. 

edge cases I can think of: 
- unmanaged views that depend on managed ones will be deleted

**Comment by anneFly** [comment]
@syphar yeah, the sync works in a way that views are synced in the right order. Views that depend on others will be synced at the end. So I cannot think of a case where it won't work. 
With the deleting of unmanaged views, you are right, I was also thinking about this...
I will make a PR to the original repository and see what they will say.

**Comment by codingjoe** [comment]
Why do we open up so many pull-requests to our Repo, didn't we switch already?
I heard the maintainer is very responsive.

**Comment by anneFly** [comment]
@codingjoe I wanted Denis to have a look first before I made a PR to the original repo. I thought a PR is the easiest way to show the changes. Anyway, this was merged to the original repo. I close this one.

**Pull request closed without merging**
